baseurl = "/"
languageCode = "zh-cn"
theme = "hello-friend"
paginate = 5
defaultContentLanguage = "cn"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "post"

  # OS theme is default when not provided, but you can force it to "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4

  # Show reading time in minutes for posts
  showReadingTime = false

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  toc = false

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true

[languages]
  [languages.cn]
    title = "Monster Cone"
    subtitle = "Monster Cone Blog"
    keywords = "hugo blog Monster Cone"
    copyright = "Copyright 2021 - 2022 by Monster Cone"
    beian = "鄂ICP备2022008661号"
    menuMore = "展示更多"
    writtenBy = "Written by"
    readMore = "阅读更多"
    readOtherPosts = "阅读其他文章"
    newerPosts = "上页"
    olderPosts = "下页"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.cn.params.logo]
      logoText = "Monster Cone"
      logoHomeLink = "/"
      # path = "/images/logo.png"
      # alt = "Monster Cone"

    [languages.cn.menu]
      [[languages.cn.menu.main]]
        identifier = "home"
        name = "首页"
        url = "/"
        weight = 1
      [[languages.cn.menu.main]]
        identifier = "tags"
        name = "标签"
        url = "/tags/"
        weight = 2
      [[languages.cn.menu.main]]
        identifier = "categories"
        name = "分类"
        url = "/categories/"
        weight = 3
