baseURL: "https://blog.dongxin.cool/"
languageCode: zh-cn
title: Monster Cone
theme: hugo-PaperMod
menu:
  main:
    - identifier: home
      name: 首页
      url: /
      weight: 1
    - identifier: archives
      name: 文章
      url: /post/
      weight: 2
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 3

taxonomies:
  category: categories
  tag: tags

params:
  author: Monster Cone
  socialIcons: # optional
    - name: "github"
      url: "https://github.com/Monster-2019"
  ShowCodeCopyButtons: true
outputs:
  home:
    - HTML
    - RSS
    - JSON